version: '3'
services:
  database:
    image: postgres:10.7
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: superrecord

  app:
    build: 
      context: ../../
      dockerfile: docker/dev/Dockerfile
    restart: on-failure
    environment:
      DATABASE_ENGINE: 'django.db.backends.postgresql'
      DATABASE_HOST: 'database'
      DATABASE_NAME: 'superrecord'
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: 'postgres'
      DATABASE_PORT: '5432'
      SECRET_KEY: 'c^-oq&0fah72+y8(-qijb9-@pbp9!$p^3pym(!&_mk%5t*a!ce'
      CODACY_PROJECT_TOKEN: "${CODACY_PROJECT_TOKEN}"
    depends_on:
      - database
    ports:
      - '8000:8000'

volumes:
  dbdata:
  
